name: place_picker_example
description: Demonstrates how to use the place_picker plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter

  place_picker:
    path: ../
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
