name: place_picker
description: Plugin place picker.
version: 0.1.8
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  uuid: ^3.0.4
  location: ^4.1.1
  yandex_geocoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # plugin:
