name: place_picker
description: Plugin place picker.
version: 0.0.4
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.2.0
  http: ^0.12.2
  uuid: ^2.2.2
  location: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # plugin:
