name: place_picker
description: Plugin place picker.
version: 0.2.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.0
  http: ^0.13.5
  uuid: ^3.0.4
  location: ^5.0.2+1
  yandex_geocoder: ^2.0.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  easy_autocomplete: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
